// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/user/bmscdc/internal/db (interfaces: DBService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/db_mock.go -package=mocks github.com/user/bmscdc/internal/db DBService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	types "github.com/user/bmscdc/internal/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDBService is a mock of DBService interface.
type MockDBService struct {
	ctrl     *gomock.Controller
	recorder *MockDBServiceMockRecorder
	isgomock struct{}
}

// MockDBServiceMockRecorder is the mock recorder for MockDBService.
type MockDBServiceMockRecorder struct {
	mock *MockDBService
}

// NewMockDBService creates a new mock instance.
func NewMockDBService(ctrl *gomock.Controller) *MockDBService {
	mock := &MockDBService{ctrl: ctrl}
	mock.recorder = &MockDBServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBService) EXPECT() *MockDBServiceMockRecorder {
	return m.recorder
}

// CreateKnock mocks base method.
func (m *MockDBService) CreateKnock(ctx context.Context, roomID, guestName string) (*types.KnockResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateKnock", ctx, roomID, guestName)
	ret0, _ := ret[0].(*types.KnockResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateKnock indicates an expected call of CreateKnock.
func (mr *MockDBServiceMockRecorder) CreateKnock(ctx, roomID, guestName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateKnock", reflect.TypeOf((*MockDBService)(nil).CreateKnock), ctx, roomID, guestName)
}

// CreateRoom mocks base method.
func (m *MockDBService) CreateRoom(ctx context.Context, meetingCode string) (*types.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, meetingCode)
	ret0, _ := ret[0].(*types.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockDBServiceMockRecorder) CreateRoom(ctx, meetingCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockDBService)(nil).CreateRoom), ctx, meetingCode)
}

// EndRoom mocks base method.
func (m *MockDBService) EndRoom(ctx context.Context, meetingCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EndRoom", ctx, meetingCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// EndRoom indicates an expected call of EndRoom.
func (mr *MockDBServiceMockRecorder) EndRoom(ctx, meetingCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EndRoom", reflect.TypeOf((*MockDBService)(nil).EndRoom), ctx, meetingCode)
}

// GetKnockRoomCode mocks base method.
func (m *MockDBService) GetKnockRoomCode(ctx context.Context, knockID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKnockRoomCode", ctx, knockID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKnockRoomCode indicates an expected call of GetKnockRoomCode.
func (mr *MockDBServiceMockRecorder) GetKnockRoomCode(ctx, knockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKnockRoomCode", reflect.TypeOf((*MockDBService)(nil).GetKnockRoomCode), ctx, knockID)
}

// GetRoomByCode mocks base method.
func (m *MockDBService) GetRoomByCode(ctx context.Context, meetingCode string) (*types.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomByCode", ctx, meetingCode)
	ret0, _ := ret[0].(*types.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomByCode indicates an expected call of GetRoomByCode.
func (mr *MockDBServiceMockRecorder) GetRoomByCode(ctx, meetingCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomByCode", reflect.TypeOf((*MockDBService)(nil).GetRoomByCode), ctx, meetingCode)
}

// StartRecording mocks base method.
func (m *MockDBService) StartRecording(ctx context.Context, roomID, egressID, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRecording", ctx, roomID, egressID, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRecording indicates an expected call of StartRecording.
func (mr *MockDBServiceMockRecorder) StartRecording(ctx, roomID, egressID, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRecording", reflect.TypeOf((*MockDBService)(nil).StartRecording), ctx, roomID, egressID, path)
}

// UpdateKnockStatus mocks base method.
func (m *MockDBService) UpdateKnockStatus(ctx context.Context, knockID, status string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateKnockStatus", ctx, knockID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateKnockStatus indicates an expected call of UpdateKnockStatus.
func (mr *MockDBServiceMockRecorder) UpdateKnockStatus(ctx, knockID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateKnockStatus", reflect.TypeOf((*MockDBService)(nil).UpdateKnockStatus), ctx, knockID, status)
}

// UpdateParticipantLeft mocks base method.
func (m *MockDBService) UpdateParticipantLeft(ctx context.Context, roomCode, identity string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateParticipantLeft", ctx, roomCode, identity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateParticipantLeft indicates an expected call of UpdateParticipantLeft.
func (mr *MockDBServiceMockRecorder) UpdateParticipantLeft(ctx, roomCode, identity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateParticipantLeft", reflect.TypeOf((*MockDBService)(nil).UpdateParticipantLeft), ctx, roomCode, identity)
}

// UpdateRecordingStatus mocks base method.
func (m *MockDBService) UpdateRecordingStatus(ctx context.Context, egressID, status string, durationSeconds int, fileSizeBytes int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRecordingStatus", ctx, egressID, status, durationSeconds, fileSizeBytes)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRecordingStatus indicates an expected call of UpdateRecordingStatus.
func (mr *MockDBServiceMockRecorder) UpdateRecordingStatus(ctx, egressID, status, durationSeconds, fileSizeBytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRecordingStatus", reflect.TypeOf((*MockDBService)(nil).UpdateRecordingStatus), ctx, egressID, status, durationSeconds, fileSizeBytes)
}

// GetUserCount mocks base method.
func (m *MockDBService) GetUserCount(ctx context.Context) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCount", ctx)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserCount indicates an expected call of GetUserCount.
func (mr *MockDBServiceMockRecorder) GetUserCount(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCount", reflect.TypeOf((*MockDBService)(nil).GetUserCount), ctx)
}
