// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/user/bmscdc/internal/livekit (interfaces: LiveKitService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/livekit_mock.go -package=mocks github.com/user/bmscdc/internal/livekit LiveKitService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	http "net/http"
	reflect "reflect"

	livekit "github.com/livekit/protocol/livekit"
	gomock "go.uber.org/mock/gomock"
)

// MockLiveKitService is a mock of LiveKitService interface.
type MockLiveKitService struct {
	ctrl     *gomock.Controller
	recorder *MockLiveKitServiceMockRecorder
	isgomock struct{}
}

// MockLiveKitServiceMockRecorder is the mock recorder for MockLiveKitService.
type MockLiveKitServiceMockRecorder struct {
	mock *MockLiveKitService
}

// NewMockLiveKitService creates a new mock instance.
func NewMockLiveKitService(ctrl *gomock.Controller) *MockLiveKitService {
	mock := &MockLiveKitService{ctrl: ctrl}
	mock.recorder = &MockLiveKitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLiveKitService) EXPECT() *MockLiveKitServiceMockRecorder {
	return m.recorder
}

// GenerateJoinToken mocks base method.
func (m *MockLiveKitService) GenerateJoinToken(roomCode, identity string, isHost bool) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateJoinToken", roomCode, identity, isHost)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateJoinToken indicates an expected call of GenerateJoinToken.
func (mr *MockLiveKitServiceMockRecorder) GenerateJoinToken(roomCode, identity, isHost any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateJoinToken", reflect.TypeOf((*MockLiveKitService)(nil).GenerateJoinToken), roomCode, identity, isHost)
}

// StartRoomCompositeEgress mocks base method.
func (m *MockLiveKitService) StartRoomCompositeEgress(ctx context.Context, roomCode, egressID, s3URL, s3Bucket, s3AccessKey, s3SecretKey, s3Key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartRoomCompositeEgress", ctx, roomCode, egressID, s3URL, s3Bucket, s3AccessKey, s3SecretKey, s3Key)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartRoomCompositeEgress indicates an expected call of StartRoomCompositeEgress.
func (mr *MockLiveKitServiceMockRecorder) StartRoomCompositeEgress(ctx, roomCode, egressID, s3URL, s3Bucket, s3AccessKey, s3SecretKey, s3Key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartRoomCompositeEgress", reflect.TypeOf((*MockLiveKitService)(nil).StartRoomCompositeEgress), ctx, roomCode, egressID, s3URL, s3Bucket, s3AccessKey, s3SecretKey, s3Key)
}

// StopEgress mocks base method.
func (m *MockLiveKitService) StopEgress(ctx context.Context, egressID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopEgress", ctx, egressID)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopEgress indicates an expected call of StopEgress.
func (mr *MockLiveKitServiceMockRecorder) StopEgress(ctx, egressID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopEgress", reflect.TypeOf((*MockLiveKitService)(nil).StopEgress), ctx, egressID)
}

// VerifyWebhookSignature mocks base method.
func (m *MockLiveKitService) VerifyWebhookSignature(r *http.Request) (*livekit.WebhookEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhookSignature", r)
	ret0, _ := ret[0].(*livekit.WebhookEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyWebhookSignature indicates an expected call of VerifyWebhookSignature.
func (mr *MockLiveKitServiceMockRecorder) VerifyWebhookSignature(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhookSignature", reflect.TypeOf((*MockLiveKitService)(nil).VerifyWebhookSignature), r)
}
