// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/user/bmscdc/internal/ws (interfaces: WSService)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/ws_mock.go -package=mocks github.com/user/bmscdc/internal/ws WSService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWSService is a mock of WSService interface.
type MockWSService struct {
	ctrl     *gomock.Controller
	recorder *MockWSServiceMockRecorder
	isgomock struct{}
}

// MockWSServiceMockRecorder is the mock recorder for MockWSService.
type MockWSServiceMockRecorder struct {
	mock *MockWSService
}

// NewMockWSService creates a new mock instance.
func NewMockWSService(ctrl *gomock.Controller) *MockWSService {
	mock := &MockWSService{ctrl: ctrl}
	mock.recorder = &MockWSServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWSService) EXPECT() *MockWSServiceMockRecorder {
	return m.recorder
}

// BroadcastToRoom mocks base method.
func (m *MockWSService) BroadcastToRoom(roomID string, message any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadcastToRoom", roomID, message)
}

// BroadcastToRoom indicates an expected call of BroadcastToRoom.
func (mr *MockWSServiceMockRecorder) BroadcastToRoom(roomID, message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastToRoom", reflect.TypeOf((*MockWSService)(nil).BroadcastToRoom), roomID, message)
}

// HandleConnection mocks base method.
func (m *MockWSService) HandleConnection(w http.ResponseWriter, r *http.Request, roomID, userID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleConnection", w, r, roomID, userID)
}

// HandleConnection indicates an expected call of HandleConnection.
func (mr *MockWSServiceMockRecorder) HandleConnection(w, r, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleConnection", reflect.TypeOf((*MockWSService)(nil).HandleConnection), w, r, roomID, userID)
}
